### ISSUE TITLE
Update for kad@1.1.0-beta.x

### ISSUE THREAD

**Issue by gordonwritescode** [omphalos/kad-localstorage#1]
To simplify storage adapter implementation, kad now serializes values to strings before passing to `storage.put` and parses into JSON after calling `storage.get`. This allows storage implementations to not worry about (de)serialization.

Looks like kad-localstorage does `JSON.parse` in put/get, so we need to remove that and just return the string.

Kad now has a `storage` metapackage that uses this lib as a dependency and is exposed at `kad.storage. LocalStorage`, so this blocks a stable 1.1.0 release. 

Relevant:

* [`kad.storage`](https://github.com/gordonwritescode/kad/blob/master/doc/storage.md)

**Comment by omphalos** [comment]
@gordonwritescode I can take care of this, unless you've already started.  Let me know.

**Comment by gordonwritescode** [comment]
Nope haven't started! Have at it, friend.
